---
- hosts: oob-mgmt-server
  roles:
  - internet
  become: true
  
- hosts: switches
  roles:
  - switch-common
  become: true

- hosts: leaf01,leaf02
  roles:
  - l3-leaf

- hosts: spines
  roles:
  - l3-spine

- hosts: leaf03,leaf04
  roles:
  - l3-leaf

- hosts: servers
  roles:
  - server-common
  become: true

- hosts: server01
  roles:
  - openstack-controller
  become: true

- hosts: server02, server03, server04
  roles:
  - openstack-compute
  become: true

- hosts: server01
  roles:
  - demo
  become: true
...
