
# Install required packages
- name: get the mitaka packages
  apt_repository:
    repo: 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/mitaka main'
    name: mitaka
    state: present

- name: install keyring
  apt:
    name: {{item}}
    state: present
    update_cache: yes
  with_items:
    - ubuntu-cloud-keyring

- name: install packages
  apt:
    pkg: {{item}}
    state: present
  with_items:
    - neutron-linuxbridge-agent
    - nova-compute
    - python-openstackclient
    - neutron-l3-agent

- name: neutron config files
  template:
    src: {{item}}.j2
    dest: /etc/neutron/{{item}}
  with_items:
      - neutron.conf

- name: neutron ml2 config files
  template:
    src: {{item}}.j2
    dest: /etc/neutron/plugins/ml2/{{item}}
  with_items:
      - linuxbridge_agent.ini

- name: nova config files
  template:
    src: {{item}}.j2
    dest: /etc/nova/{{item}}
  with_items:
      - nova.conf
      - nova-compute.conf

- name: start neutron compute and nova compute
  service:
    name={{ item }}
    state=restarted
    enabled=true
  with_items:
      - neutron-linuxbridge-agent
      - neutron-l3-agent
      - nova-compute

- name: wait for neutron and nova to wake up
  pause: seconds=10
  