---

- name: Install neutron and nova
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python-openstackclient
  - neutron-linuxbridge-agent
  - nova-compute
  - neutron-l3-agent

- name: neutron config files
  template:
    src: "{{ item }}.j2"
    dest: /etc/neutron/{{ item }}
  with_items:
  - neutron.conf

- name: neutron ml2 config files
  template:
    src: "{{ item }}.j2"
    dest: /etc/neutron/plugins/ml2/{{ item }}
  with_items:
  - linuxbridge_agent.ini

- name: nova config files
  template:
    src: "{{ item }}.j2"
    dest: /etc/nova/{{ item }}
  with_items:
  - nova.conf
  - nova-compute.conf

- name: start neutron compute and nova compute
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
  - neutron-linuxbridge-agent
  - neutron-l3-agent
  - nova-compute

- name: wait for neutron and nova to wake up
  pause:
    seconds: 10

...
