- name: nova config files
  template: src={{item}}.j2 dest=/etc/nova/{{item}}
  with_items:
      - nova.conf
      - nova-compute.conf
  notify: restart nova compute

- name: flush handlers in case of changed config
  meta: flush_handlers

- name: start nova compute
  service: name={{ item }} state=started enabled=true
  with_items:
      - nova-compute

- name: wait for nova to wake up
  pause: seconds=10
