- name: create environment scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/cumulus/{{ item }}"
    mode: 0777
  with_items:
  - admin-openrc
  - demo-openrc

# Create the m1.nano machine definition
#
- name: collect flavors
  command: openstack {{ openstack.admin_credentials }} flavor list
  register: _flavors

- name: add m1.nano flavor
  command: openstack {{ openstack.admin_credentials }} flavor create --id 0 --vcpus 1 --ram 64 --disk 1 m1.nano
  when: "'m1.nano' not in _flavors.stdout"

# add security group rules for access
#
- name: add icmp security rule
  command: openstack {{ openstack.admin_credentials }} security group rule create --proto icmp default
  when: "'m1.nano' not in _flavors.stdout"

- name: add ssh security rule
  command: openstack {{ openstack.admin_credentials }} security group rule create --proto tcp --dst-port 22 default
  when: "'m1.nano' not in _flavors.stdout"

- name: add icmp security rule for demo user
  command: openstack {{ openstack.demo_credentials }} security group rule create --proto icmp default
  when: "'m1.nano' not in _flavors.stdout"

- name: add ssh security rule for demo user
  command: openstack {{ openstack.demo_credentials }} security group rule create --proto tcp --dst-port 22 default
  when: "'m1.nano' not in _flavors.stdout"

# Create the provider network
#
- name: add provider network for neutron
  command: openstack {{ openstack.admin_credentials }} network create --share --external --provider-physical-network provider --provider-network-type flat provider
  when: "'m1.nano' not in _flavors.stdout"

# - name: make provider network routable
#   command: openstack {{ openstack.admin_credentials }} net-update provider --router:external
#   when: "'m1.nano' not in _flavors.stdout"

- name: add subnet to provider network
  command: openstack {{ openstack.admin_credentials }} subnet create --network provider --allocation-pool start={{ openstack.provider_network.start }},end={{ openstack.provider_network.end }} --dns-nameserver 8.8.4.4 --gateway {{ openstack.provider_network.gateway }} --subnet-range {{ openstack.provider_network.cidr }} provider 
  when: "'m1.nano' not in _flavors.stdout"


# Deploy a small system for evaluation with CITC
#
- name: collect flavors
  command: openstack {{ openstack.admin_credentials }} network list
  register: _networks

- name: Create demo net
  command: openstack {{ openstack.admin_credentials }} network create demonet
  when: "'demonet' not in _networks.stdout"

- name: Define demonet subnet
  command: openstack {{ openstack.admin_credentials }} subnet create --network demonet --subnet-range 200.0.0.0/24 --dns-nameserver 8.8.8.8 --gateway 200.0.0.1 demonet
  when: "'demonet' not in _networks.stdout"

- name: Create router to get in/out
  command: openstack {{ openstack.admin_credentials }} router create demorouter
  when: "'demonet' not in _networks.stdout"

- name: Connect the router to demonet
  command: openstack {{ openstack.admin_credentials }} router add subnet demorouter demonet
  when: "'demonet' not in _networks.stdout"

- name: Connect the router to the provider network
  command: openstack {{ openstack.admin_credentials }} router set --external-gateway provider demorouter
  when: "'demonet' not in _networks.stdout"

- name: Connect the router to the provider network
  command: openstack {{ openstack.admin_credentials }} server create --flavor m1.nano --image cirros --nic net-id=demonet {{ item }}
  with_items:
  - cirros1
  - cirros2
  when: "'demonet' not in _networks.stdout"

- name: get a floating IP address
  command: openstack {{ openstack.admin_credentials }} floating ip create provider
  register: _floating_ip
  when: "'demonet' not in _networks.stdout"

- name: Assign it to the cirros1
  command: openstack {{ openstack.admin_credentials }} server add floating ip cirros1 192.168.0.102
  when: "'demonet' not in _networks.stdout"

