#-------------------------------------------------------------------------------
#
# Copyright 2017 Cumulus Networks Inc.  All rights reserved
#
#-------------------------------------------------------------------------------
#
# Broken into separate files because there are some gnarly steps involved with
# some of these.
#

- name: Common OpenStack Packages
  apt:
    name: python-openstackclient
    state: present

- include: mysql.yaml
- include: rabbitmq.yaml
- include: memcached.yaml
- include: openstack-keystone.yaml
- include: openstack-glance.yaml
- include: openstack-neutron-controller.yaml
# - include: openstack-nova-controller.yaml
# - include: openstack-horizon.yaml
# - include: openstack-initial-config.yaml
