---

# Install and prep horizon
#
- name: Install horizon
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - openstack-dashboard

- name: horizon config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/openstack-dashboard/{{ item }}"
  with_items:
  - local_settings.py

- name: restart apache2
  service:
    name: apache2
    state; restarted
    enabled: true

...
