#
# Prepare the DC/OS slave nodes
#

- set_fact:
    myvars: "{{ servervars[inventory_hostname] }}"

- name: get mesos, zookeeper, and docker-ce
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
  - zookeeper
  - mesos
  - docker-ce

- name: stop services
  service:
    name: zookeeper
    state: stopped
  become: yes
- service:
    name: mesos-master
    state: stopped
  become: yes
- service:
    name: mesos-slave
    state: stopped
  become: yes

- name: setup zookeeper
  template:
    src: zk.j2
    dest: /etc/mesos/zk
    owner: root
    group: root
    mode:
  become: true

- name: setup mesos
  template:
    src: ip.j2
    dest: /etc/mesos-slave/ip
    owner: root
    group: root
    mode:
  become: true
- template:
    src: hostname.j2
    dest: /etc/mesos-slave/hostname
    owner: root
    group: root
    mode:
  become: true
- template:
    src: containerizers.j2
    dest: /etc/mesos-slave/containerizers
    owner: root
    group: root
    mode:
  become: true
- template:
    src: executor_registration_timeout.j2
    dest: /etc/mesos-slave/executor_registration_timeout
    owner: root
    group: root
    mode:
  become: true

- name: start services
  service:
    name: mesos-slave
    enabled: yes
    state: started
  become: yes
