#
# Prepare the DC/OS master node
#

- set_fact:
    myvars: "{{ servervars[inventory_hostname] }}"

- name: get mesosphere (used to be a meta package)
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
  - mesos
  - zookeeper
  - chronos
  - marathon
  
- name: setup zookeeper
  template:
    src: zk.j2
    dest: /etc/mesos/zk
    owner: root
    group: root
    mode:
  become: true
- template:
    src: myid.j2
    dest: /etc/zookeeper/conf/myid
    owner: root
    group: root
    mode:
  become: true
- blockinfile:
    path: /etc/zookeeper/conf/zoo.cfg
    insertafter: "#server."
    block: |
      server.1={{ myvars.V4 }}:2888:3888
  become: true

- name: setup mesos
  template:
    src: quorum.j2
    dest: /etc/mesos-master/quorum
    owner: root
    group: root
    mode:
  become: true
- template:
    src: ip.j2
    dest: /etc/mesos-master/ip
    owner: root
    group: root
    mode:
  become: true
- template:
    src: hostname.j2
    dest: /etc/mesos-master/hostname
    owner: root
    group: root
    mode:
  become: true

- name: setup marathon
  file:
    path: /etc/marathon/conf
    state: directory
  become: true
- template:
    src: marathon.conf.j2
    dest: /etc/marathon/conf/hostname
    owner: root
    group: root
    mode:
  become: true
- template:
    src: marathon.master.j2
    dest: /etc/marathon/conf/master
    owner: root
    group: root
    mode:
  become: true
- template:
    src: marathon.zk.j2
    dest: /etc/marathon/conf/zk
    owner: root
    group: root
    mode:
  become: true
- template:
    src: marathon.task_launch_timeout.j2
    dest: /etc/marathon/conf/task_launch_timeout
    owner: root
    group: root
    mode:
  become: true

- name: Restart services
  service:
    name: mesos-slave
    state: stopped
  become: yes
- template:
    src: mesos-slave.override.j2
    dest: /etc/init/mesos-slave.override
    owner: root
    group: root
    mode:
  become: true
- service:
    name: zookeeper
    enabled: yes
    state: restarted
  become: yes
- service:
    name: mesos-master
    enabled: yes
    state: started
  become: yes
- service:
    name: marathon
    enabled: yes
    state: started
  become: yes
